name: Deploy to Vercel

on:
  push:
    branches: [ main ]

jobs:
  vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./next-app
        run: npm ci

      - name: Run linting
        working-directory: ./next-app
        run: npm run lint

      - name: Build Next.js
        working-directory: ./next-app
        run: npm run build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-arg: '--prod'
          working-directory: ./next-app
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
